blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/adapticai/new-starter/discussions
    about: Please ask and answer questions in Discussions
  - name: Documentation
    url: https://github.com/adapticai/new-starter/tree/main/docs
    about: Check our documentation for guides and references
  - name: Community Discord
    url: https://discord.gg/adapticai
    about: Join our Discord community for real-time help